# Generated by Django 5.0 on 2023-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contcat',
            name='desc',
            field=models.TextField(default='enter', max_length=500),
            preserve_default=False,
        ),
    ]
